---
- name: Download wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp-cli
    mode: 0755
  tags: wp-cli

- name: Create a wp-cli packages directory
  file: 
    path: /usr/local/lib/wp-cli-packages
    state: directory
  tags: wp-cli

- name: Create a wrapper around wp-cli
  copy:
    content: | 
      #!/bin/sh
      export WP_CLI_PACKAGES_DIR=/usr/local/lib/wp-cli-packages
      /usr/local/bin/wp-cli "$@"
    dest: /usr/local/bin/wp
    mode: 0755
  tags: wp-cli

- name: Install the wp-login-cli package
  command: wp --allow-root package install aaemnnosttv/wp-cli-login-command
  args:
    creates: /usr/local/lib/wp-cli-packages/vendor/aaemnnosttv/wp-cli-login-command/wp-cli.yml
  tags: 
    - wp-cli
    - debug
