incoming_ports:
  - { port: 22, name: 'SSH' }
  - { port: 80, name: 'HTTP' }
  - { port: 443, name: 'HTTPS' }
  - { port: 5665, name: 'Icinga2' }

outgoing_ports:
  - { port: 22, protocol: tcp, name: 'SSH' }
  - { port: 25, protocol: tcp, name: 'SMTP' }
  - { port: 80, protocol: tcp, name: 'HTTP' }
  - { port: 443, protocol: tcp, name: 'HTTPS' }
  - { port: 5665, protocol: tcp, name: 'Icinga2' }
  - { port: 10022, protocol: tcp, name: 'Megaphone git SSH' }
  - { port: 53, protocol: udp, name: 'DNS' }
