- name: Show the site in question
  debug:
    msg: Extensions for "{{ item.0.item.key }}"

- name: deleteme
  debug:
    var: item.1

- debug: 
    msg: "{{ inner_item.name }} {{ inner_item.version }}"
  with_items: "{{ item.1 | from_json | list }}"
  loop_control:
    loop_var: inner_item

